import Head from "next/head";
import { useRouter } from "next/router";
import { Button, Box, Container, Heading, Text } from "@chakra-ui/react";

export default function Home() {
  const router = useRouter();
  const getId = () => {
    fetch(`${process.env.NEXT_PUBLIC_SERVER_URL}/create`)
      .then((response) => response.json())
      .then((data) => {
        router.push(data.id);
      })
      .catch((err) => alert(err));
  };
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container maxW="4xl" mt={4} mx="auto">
        <Heading mb={2}>Hello!</Heading>
        <Box my={2}>
          <Text>
            Ever needed a temporary endpoint where you need to see the incoming
            request and payload?
          </Text>
          <Text>
            I know this may be oddly specific, but from time to time I needed it
            seems.
          </Text>
          <Text>
            Simply click the button below and use the URL in the address bar to
            see what is coming.
          </Text>
          <Text>No need to refresh!</Text>
        </Box>
        <Button colorScheme="blue" mt={2} onClick={getId}>
          Get ID
        </Button>
      </Container>
    </div>
  );
}
